apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog-content
        image: ghost
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://blog.instituteofai.com
        - name: mail__transport
          value: SMTP
        - name: mail__options__service
          value: Mailgun
        - name: mail__options__auth__user
          value: <mailgun_user>
        - name: mail__options__auth__pass
          value: <mailgun_password>
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: $(MYSQL_SERVICE_HOST)
        - name: database__connection__port
          value: $(MYSQL_SERVICE_PORT)
        - name: database__connection__user
          value: <mysql_user>
        - name: database__connection__password
          value: <mysql_password>
        - name: database__connection__database
          value: ghost

