apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: iai-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
      - blog.instituteofai.com
    secretName: iai-blog-tls
  - hosts:
      - certifications.instituteofai.com
    secretName: iai-cert-verify-tls
  rules:
  - host: blog.instituteofai.com
    http:
      paths:
      - path: /
        backend:
          serviceName: blog
          servicePort: 8085
  - host: certifications.instituteofai.com
    http:
      paths:
      - path: /
        backend:
          serviceName: iai-certificate-verifier
          servicePort: 8888
